import type { Metadata } from 'next'
import { BIZ_UDPGothic } from 'next/font/google'
import './globals.css'
import { SWRProvider } from './swr-provider'

const font = BIZ_UDPGothic({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SWRProvider>
      <html lang="ja">
        <body className={font.className}>{children}</body>
      </html>
    </SWRProvider>
  )
}
